CREATE TYPE point_type_enum AS ENUM ('MAIN', 'SECONDARY');
CREATE TYPE vehicles_status_enum AS ENUM ('AVAILABLE', 'RENTED', 'CHARGING');
CREATE TYPE tarif_type_enum AS ENUM ('HOURLY', 'SUBSCRIPTION');
CREATE TYPE discount_type_enum AS ENUM ('PERCENTAGE', 'FIXED');